"use strict";

/**
 * Canonical module permission keys shared by app routes and bootstrap seeds.
 * Keep in sync with dashboard MODULE_KEY_BY_ID where applicable.
 */
const MODULE_KEYS = {
  ADMISSION: "admission",
  REGISTRATION: "register-center",
  ACCESS_CONTROL: "access-control",
  SECURITY_AUDIT: "security-audit",
  SYSTEM_OPS_CENTER: "system-ops-center",
  SYSTEM_INCIDENT_RESPONSE: "system-incident-response",
  INSTITUTIONS_USERS_REGISTRY: "institutions-users-registry",
  RECYCLE_BIN: "recycle-bin",
  CBC_CURRICULUM_EDITOR: "cbc-curriculum-editor",
  MANAGEMENT_TEACHERS: "management-teachers",
  MANAGEMENT_NON_TEACHING: "management-non-teaching",
  STAFF_SERVICE_PROVIDERS: "staff-service-providers",
  MANAGEMENT_BOM: "management-bom",
  MANAGEMENT_SERVICE_PROVIDERS: "management-service-providers",
  MANAGEMENT_TEACHER_RESOURCES: "management-teacher-resources",
  ATTENDANCE: "attendance",
  ACADEMIC_EXAMS: "academic-exams",
  ACADEMIC_MARKS: "academic-marks",
  HR_LEAVE: "hr-leave",
  HR_RECRUITMENT: "hr-recruitment",
  FINANCE_FEE_STRUCTURE: "finance-fee-structure",
  FINANCE_FEE_PAYMENTS: "finance-fee-payments",
  FINANCE_PROCUREMENT: "finance-procurement",
  FINANCE_PAYROLL: "finance-payroll",
  FINANCE_SALARY_ADVANCE: "finance-salary-advance",
  COMMUNICATION_ANNOUNCEMENTS: "communication-announcements",
  COMMUNICATION_MESSAGES: "communication-messages",
  LEARNER_RESOURCES: "learner-resources",
  WELFARE_MEMBERS: "welfare-members",
  WELFARE_CONTRIBUTIONS: "welfare-contributions",
  WELFARE_LOANS: "welfare-loans",
  LAWS: "laws",
  DASHBOARD: "dashboard",
  DASHBOARD_ALERTS_ANNOUNCEMENTS: "dashboard-alerts-announcements",
  DASHBOARD_ATTENDANCE_LIST: "dashboard-attendance-list",
  DASHBOARD_PERFORMANCE: "dashboard-performance",
  DASHBOARD_FEE_COLLECTION: "dashboard-fee-collection",
  DASHBOARD_OUTSTANDING_BALANCES: "dashboard-outstanding-balances",
  SEARCH: "search",
  PARENT_RESULTS: "parent-results",
  LEARNER_MATERIALS: "learner-materials",
  ADMISSION_REGISTER: "admission-register",
  ADMISSION_FORM: "admission-form",
  ADMISSION_LETTER: "admission-letter",
  ADMISSION_BIO_DATA_BULK_UPLOAD: "admission-bio-data-bulk-upload",
  ATTENDANCE_TEACHER_REGISTER: "attendance-teacher-register",
  ATTENDANCE_SUPPORT_STAFF_REGISTER: "attendance-support-staff-register",
  ATTENDANCE_LEARNER_REGISTER: "attendance-learner-register",
  STAFF_PROFILE_TEACHER: "staff-profile-teacher",
  STAFF_PROFILE_SUPPORT_STAFF: "staff-profile-support-staff",
  REGISTER_INSTITUTION: "register-institution",
  REGISTER_USERS: "register-users",
  SECURITY_LOGIN_AUDIT: "security-login-audit",
  INSTITUTION_LETTERHEAD_UPLOAD: "institution-letterhead-upload",
  INSTITUTION_UPLOADS: "institution-uploads",
  HR_INSTITUTIONAL_LETTERS: "hr-institutional-letters",
  FINANCE_FEE_STATUS: "finance-fee-status",
  INSTITUTIONAL_REGISTERS: "institutional-registers"
};

module.exports = { MODULE_KEYS };
